services:

  postgres:
    image: postgres:18-alpine
    container_name: elab-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: elab
      POSTGRES_PASSWORD: elab_dev_password
      POSTGRES_DB: elab

    ports:
      - "5432:5432"

    volumes:
      - elab_postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U elab -d elab
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:8.2-alpine
    container_name: elab-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - elab_redis_data:/data


volumes:
  elab_postgres_data:
  elab_redis_data:
